CREATE DATABASE IF NOT EXISTS database;
-- CREATE DATABASE IF NOT EXISTS miranda_web;
CREATE USER IF NOT EXISTS 'miranda'@'%' IDENTIFIED BY 'miranda_123';
GRANT ALL ON *.* TO 'miranda'@'%' WITH GRANT OPTION;